# type: ignore
#
# This file is part of the GNU Radio LLM project.
#

import inspect

from importlib.util import spec_from_file_location, module_from_spec
from pathlib import Path

from typing import Any, Tuple, Type

from gnuradio import gr
from gnuradio.gr.top_block import top_block
from gnuradio.grc.core.platform import Platform
from gnuradio.grc.core.generator.top_block import TopBlockGenerator

from flowgraph.schema import Flowgraph


def load_top_block(path: Path) -> Tuple[Any, Type[top_block]]:
    spec = spec_from_file_location('flowgraph_module', str(path))
    if spec is None or spec.loader is None:
        raise ImportError(f'Could not load flowgraph module from {path}')
    module = module_from_spec(spec)
    spec.loader.exec_module(module)

    # Try to find main()
    main_func = getattr(module, 'main', None)
    if main_func is None or not callable(main_func):
        raise ValueError('No main function found in flowgraph script')

    # Check the default arguments generated by GRC
    signature = inspect.signature(main_func)
    top_block_cls = None
    if 'top_block_cls' in signature.parameters:
        default = signature.parameters['top_block_cls'].default
        if inspect.isclass(default) and issubclass(default, top_block):
            top_block_cls = default

    if top_block_cls is None:
        raise ValueError('Could not infer top_block class from main signature')

    return (main_func, top_block_cls)


def generate_flowgraph(flowgraph: Flowgraph) -> Path:
    platform = Platform(
        version=gr.version(),
        version_parts=(
            gr.major_version(),
            gr.api_version(),
            gr.minor_version()),
        prefs=gr.prefs(),
        install_prefix=gr.prefix()
    )
    platform.build_library()
    grc_flowgraph = platform.make_flow_graph()
    grc_flowgraph.import_data(flowgraph.model_dump())
    grc_flowgraph.rewrite()
    grc_flowgraph.validate()

    if not grc_flowgraph.is_valid():
        raise ValueError('Invalid flowgraph')

    generator = TopBlockGenerator(grc_flowgraph, tempfile.gettempdir())
    generator.write()
    return Path(generator.file_path)
