name: GNU Radio LLM Unit Tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Micromamba
              uses: mamba-org/setup-micromamba@v1
              with:
                  environment-file: environment.yml
                  cache-downloads: true
                  cache-environment: true
                  condarc: |
                      channels:
                          - conda-forge
                          - defaults

            - name: Run pytest
              shell: bash
              run: |
                  export PYTHONPATH=$PYTHONPATH:$(pwd)
                  micromamba run -n gnuradio-llm pytest tests/ --maxfail=5 --disable-warnings -q
